[package]
name = "fix-gnupg-permissions"
version = "0.7.0"
authors = ["Billie Thompson <billie+fix-gnupg-permissions@billiecodes.com>"]
edition = "2018"
description = "Fix the permissions on the GnuPG config directory."
license = "Creative Commons Zero v1.0 Universal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0.2"
clap = "~2.33"
[dev-dependencies]
tempfile = "3"
