[package]
name = "fix-gnupg-permissions"
version = "0.4.0"
authors = ["Billie Thompson <billie@billiecodes.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0.2"
clap = "~2.33"
[dev-dependencies]
tempfile = "3"
